#!/bin/sh

## (c) 2014 Frédéric Gaudet. Based on :
## live-config(7) - System Configuration Scripts
## Copyright (C) 2006-2013 Daniel Baumann <daniel@debian.org>
## Copyright (C) 2021 Jongkyung woo <jkwoo@gooroom.kr>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.

Cmdline ()
{
	# Reading kernel command line
	for _PARAMETER in ${LIVE_CONFIG_CMDLINE}
	do
		case "${_PARAMETER}" in
			live-config.locales=*|locales=*)
			LIVE_LOCALES="${_PARAMETER#*locales=}"
			;;
		esac
	done
}

Init ()
{
	# Checking if package is installed or already configured
	if [ ! -e /var/lib/dpkg/info/gooroom-guide.list ] || \
	   [ -e /var/lib/live/config/gooroom-guide ]
	then
		exit 0
	fi

	echo -n "Installer_icon"
}

Installer_icon()
{
	DESKTOP_FILE=debian-installer-launcher.desktop
	if [ -e /usr/share/applications/$DESKTOP_FILE ]
	then
		sudo -u "${LIVE_USERNAME}" sh -c "umask 0077 && mkdir -p /home/${LIVE_USERNAME}/Desktop && sed -e's/Exec=su.*$/Exec=sudo \/usr\/bin\/live-installer/' /usr/share/applications/${DESKTOP_FILE} > /home/${LIVE_USERNAME}/Desktop/${DESKTOP_FILE}"
	fi

	# Creating state file
	touch /var/lib/live/config/installer-icon
}

Cmdline
Init
Installer_icon
