#!/bin/sh

## live-config(7) - System Configuration Components
## Copyright (C) 2006-2015 Daniel Baumann <mail@daniel-baumann.ch>
## Copyright (C) 2021 Jongkyung Woo <jkwoo@gooroom.kr>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


#set -e

Cmdline ()
{
	# Reading kernel command line
	for _PARAMETER in ${LIVE_CONFIG_CMDLINE}
	do
		case "${_PARAMETER}" in
			live-config.username=*|username=*)
				LIVE_USERNAME="${_PARAMETER#*username=}"
				;;
		esac
	done
}

Init ()
{
	# Checking if package is installed or already configured
	if [ ! -e /var/lib/dpkg/info/gooroom-guide.list ] || \
	   [ -e /var/lib/live/config/gooroom-guide ]
	then
		exit 0
	fi

	echo -n " gooroom-guide"
}

Config ()
{
	if [ ! -e /home/${LIVE_USERNAME}/.config/gooroom/gooroom-guide/norun ]
	then
		sudo -u "${LIVE_USERNAME}" sh -c "umask 0077 && mkdir -p /home/${LIVE_USERNAME}/.config/gooroom/gooroom-guide && cat > /home/${LIVE_USERNAME}/.config/gooroom/gooroom-guide/norun" << EOF
live-installer: norun
EOF
	fi

	# Creating state file
	touch /var/lib/live/config/gooroom-guide
}

Cmdline
Init
Config
